# 第一章 异常处理

>异常处理是C++的主要特征之一，是考虑问题和处理错误的一种更好的方式。使用异常处理：

>>错误处理的代码不再冗长乏味，并且不再与“正常”代码混合在一起

>>错误代码不能被忽略

## 1.1 传统的错误处理

>从函数中返回错误状态信息、设置全局的错误信息变量。

>信号处理系统，signal和arise。

>setjump/longjump

>jump与goto是不能识别C++对象，无法自动调用对应的析构和构造函数。

## 1.2 抛出异常

>throw将导致一系列的事情发生：

>>创建程序所抛出对象的一个拷贝

>>交错返回机制

>>栈反解

>>为每一种不同的异常抛出不同类型的对象

## 1.3 捕获异常

>是程序员在一个地方专注于所要解决的问题，而在另一个地方对这个代码所产生的错误进行处理。

### 1.3.1 try块

>try 中进行正常逻辑的编写

### 1.3.2 异常处理器

>异常处理器紧接着try块，并且由关键字catch标识

>一旦某个异常被抛出，异常处理机制将会依次寻找参数类型与异常类型相匹配的异常处理器。

### 1.3.3 终止和恢复

>终止模型中，发生异常之后不可能自动恢复程序的执行

>恢复模型中，借助与while进行不断try，但是用处并不是很大

## 1.4 异常匹配

>一个对象或者是指向派生类对象的引用都会与其基类处理器匹配

>以对象的方式传递异常给基类处理块，会导致切割

>在匹配过程中不会将一种异常自动转成另一种异常

>组织顺序尽量由先派生类处理器，到基类处理器，不然所有的异常都会在基类处理器中被拦截

>通常情况下应在异常处理器中使用引用参数而不是值参数，以防止异常对象所包含的信息被切割掉

### 1.4.1 捕获所有异常

```
catch(...){
}
```

>用 ... 作为异常处理器的参数列表可以实现捕捉所有类型的异常

>最好将这个方式放在异常处理的最后，避免架空它后面的异常处理器

>不允许接受任何参数，所以无法得到任何有关异常的信息，也无法知道异常的类型

### 1.4.2 重新抛出异常

>在一个异常处理器内部，使用不带参数的throw语句可以重新抛出异常

### 1.4.3 不捕获异常

>如果try之后的异常处理器并不能匹配类型，那么将向上层进行抛出，直到该异常被处理掉

>terminate函数

>>没有任何一个层次的异常处理器可以捕获该异常的时候，会调用库函数terminate ，其调用abort终止进程

>set_terminater函数

>>设置自己的terminate函数返回原本的terminate函数指针。

>>自定义的函数不可以有参数，返回值必须为void，不能返回，不能抛出异常

>terminate函数被调用意味着问题无法解决了。

## 1.5 清理

>C++异常处理必须确保当程序执行流程离开一个作用域的时候，对于这个作用域的所有由构造函数建立起来的对象，他们的析构函数一定会被调用

### 1.5.1 资源管理

>构造函数中发生异常，则对于已经分配的资源，由于无法调用析构函数，则会导致资源的泄露。

### 1.5.2 使所有实物都成为对象

>为了防止资源泄露，必须使用下列之一来防止“不成熟的”资源分配方式：

>>在构造函数中捕获异常，用于释放资源

>>在对象的构造函数中分配资源，并且在对象的析构函数中释放资源

>使用模板可以使对象的每一次资源分配都具有原子性

### 1.5.3 auto_ptr

>是一个可以将申请到的资源自动释放的模板

```
 #include <iostream>
 #include <vector>
 #include <new>
 #include <memory>
 #include <typeinfo>
using namespace std;
class TraceHeap{
    int i;
public:
    static void *operator new(size_t size){
        void *p = ::operator new(size);
        cout<<"allocating traceHeap Object on the heap "<<"at address "<<p<<endl;
        return p;
    }
    static void operator delete(void *p){
        cout<< "delete traceHeadp object at address "<<p<<endl;
        ::operator delete(p);
    }
    TraceHeap(int i):i(i){}
    int getValue()const{return i;}
};
void g(){
    auto_ptr<TraceHeap> obj(new TraceHeap(5));
    cout<<obj->getValue()<<endl;
}
int main()
{
    g();
    return 0;
}
```

### 1.5.4 函数级的try块

>构造函数的块级try-catch

```
#include <iostream>
#include <vector>
#include <new>
#include <memory>
#include <typeinfo>
using namespace std;
class Base
{
    int i;
public:
    class BaseExcept{};
    Base(int i):i(i) {throw BaseExcept();}
};
class Derived:public Base
{
public:
    class DerivedExcept{
        const char* msg;
    public:
        DerivedExcept(const char*msg):msg(msg){}
        const char* what()const{return msg;}
    };

    Derived(int j)try: Base(j) {
        cout<<"this won't print."<<endl;

    }catch(BaseExcept &){
        throw DerivedExcept("base subobject throw.");
    }
};

int main()
{
    try{
        Derived d(3);
    }catch(Derived::DerivedExcept &d){
        cout <<d.what()<<endl;
    }
    return 0;
}

```

>普通函数的try-catch

```
#include <iostream>
#include <vector>
#include <new>
#include <memory>
#include <typeinfo>
using namespace std;

int main()try
{
    throw "main";
    return 0;
}catch (const char* msg){
    cout<<msg<<endl;
    return -1;
}
```

## 1.6 标准异常

>基类 exception

>>派生类 logic_error

>>>domain_error、invalid_arguement、length_error、out_of_range、bad_cast、bad_typeid

>>派生类 runtime_error

>>>range_error、 overflow_error、 bad_alloc

## 1.7 异常规格说明

>可选的异常规格说明，函数声明的修饰符，卸载函数参数列表后面

>函数可能抛出的可能异常类型应该写在throw之后的括号中：void f() throw(toobig, toosmall, divzero);

>void f();意味着可能抛出任何类型的异常

>void f() throw();意味着不会抛出任何异常

>好的编码策略，好的文档和便于函数调用，在编写可能抛出异常的函数时，最好使用异常规格说明。

>>unexpected函数，异常规格说明集中不包含的异常类型，会调用该函数。默认会调用terminate函数

>>set_unexpected函数，类似与之前的set_terminate

>unexpected函数也可以继续飘出异常，但是要考虑如下情况

>>异常规格说明书中包括std::bad_exception，那么被抛出的异常会被替换成std::bad_exception对象

>>反之不包括，那么会调用terminate函数

### 1.7.1 更好的异常规格说明

### 1.7.2 异常规格说明和继承

>派生的函数声明中不可以增加，只可以减少或者没有异常说明规则集

>异常说明集必须满足is-a。否则不能通过编译

### 1.7.3 什么时候不适用异常规格说明

>异常规格说明主要是为非模板类准备的

## 1.8 异常安全

## 1.9 在编程中使用异常

### 1.9.1 什么时候避免异常

>不要在异步事件中使用异常

>不要在处理简单错误的时候使用异常

>不要将异常用于程序的流程控制

>不要强迫自己使用异常

>新异常，老代码

### 1.9.2 异常的典型应用

下列情况请使用异常：

>修正错误并且重新调试产生异常的函数

>在重新调试中的函数外面补偿一些行为以便使得程序得以继续执行

>在当前语境中做尽可能多的事情，把同样类型的异常重新抛出到更高层的语境中

>在当前语境中做尽可能多的事情，并将一个不同类型的异常抛出到更高层的语境中

>终止程序

>将使用普通错误处理模式的函数，封装起来，以便用异常来替代原有的错误处理模式

>简化

>使建立的库和程序更安全

什么时候使用异常规格说明

从标准异常开始

嵌套用户自己的异常

使用异常层次结构

多重继承

通过引用而不是通过值来捕获异常

在构造函数中抛出异常

不要在析构函数内出发异常

避免悬挂指针。

## 1.10 使用异常造成的开销

>反正就是会有大开销，不要将异常用在流程控制上就对了。

>将throw看做一个特殊的系统函数调用，会需要一系列的依赖设置，会执行许多处理清理工作


